alter table public.financial_payments
  add column if not exists payment_token uuid not null default gen_random_uuid(),
  add column if not exists provider text,
  add column if not exists provider_status text,
  add column if not exists provider_order_nsu text,
  add column if not exists provider_checkout_url text,
  add column if not exists provider_transaction_nsu text,
  add column if not exists provider_invoice_slug text,
  add column if not exists provider_receipt_url text,
  add column if not exists provider_payload jsonb,
  add column if not exists link_created_at timestamptz,
  add column if not exists confirmed_at timestamptz;

create unique index if not exists financial_payments_payment_token_idx
  on public.financial_payments (payment_token);

create unique index if not exists financial_payments_provider_order_idx
  on public.financial_payments (provider, provider_order_nsu)
  where provider_order_nsu is not null;

create unique index if not exists financial_payments_provider_transaction_idx
  on public.financial_payments (provider, provider_transaction_nsu)
  where provider_transaction_nsu is not null;

alter table public.financial_payments
  drop constraint if exists financial_payments_provider_check;

alter table public.financial_payments
  add constraint financial_payments_provider_check
  check (provider is null or provider in ('infinitepay', 'manual'));

alter table public.financial_payments
  drop constraint if exists financial_payments_provider_status_check;

alter table public.financial_payments
  add constraint financial_payments_provider_status_check
  check (provider_status is null or provider_status in ('creating', 'pending', 'paid', 'failed', 'expired', 'refunded', 'disputed'));

create table if not exists public.payment_webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  event_key text not null,
  order_nsu text,
  transaction_nsu text,
  payload jsonb not null,
  processing_status text not null default 'received',
  error_message text,
  created_at timestamptz not null default now(),
  processed_at timestamptz,
  constraint payment_webhook_events_provider_check
    check (provider in ('infinitepay')),
  constraint payment_webhook_events_status_check
    check (processing_status in ('received', 'processed', 'rejected', 'duplicate')),
  unique (provider, event_key)
);

create index if not exists payment_webhook_events_order_idx
  on public.payment_webhook_events (provider, order_nsu);

alter table public.payment_webhook_events enable row level security;

revoke all on public.payment_webhook_events from anon, authenticated;
revoke all on sequence public.payment_webhook_events_id_seq from anon, authenticated;

revoke update on public.financial_payments from authenticated;
grant update (
  status,
  amount_paid_cents,
  paid_at,
  note,
  recorded_by,
  updated_at
) on public.financial_payments to authenticated;

revoke insert on public.financial_payments from authenticated;
grant insert (
  event_id,
  athlete_id,
  status,
  amount_paid_cents,
  paid_at,
  note,
  recorded_by,
  updated_at
) on public.financial_payments to authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'financial_payments'
  ) then
    alter publication supabase_realtime add table public.financial_payments;
  end if;
end
$$;
